### ISSUE TITLE
exe

### ISSUE THREAD

**Issue by xxxdbb110** [zero0mum/cartoon_crawler#3]
您好！第一次使用exe文件，提示：

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 799, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 715, in urlopen
  File "urllib3\connectionpool.py", line 404, in _make_request
  File "urllib3\connectionpool.py", line 1058, in _validate_conn
  File "urllib3\connection.py", line 419, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "漫画爬虫.py", line 102, in <module>
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
报错信息如上，请按下任意键退出...

**Comment by zero0mum** [comment]
是不是挂着vpn呢，关掉vpn试试？

**Comment by zero0mum** [comment]
是不是挂着vpn呢，关掉vpn试试？

**Comment by xxxdbb110** [comment]
没有挂VPN

**Comment by zero0mum** [comment]
try:
  res_url = r.get('https://zero0mum.github.io/web/others/sites.json')#获取网站列表
except:
  traceback.print_exc()
  input('报错信息如上，请按下任意键退出...')
else:
  print('拉取成功！')

报错的是代码102行获取网站列表这一行，试试直接用浏览器访问github这个静态网页托管的链接看看有问题么：https://zero0mum.github.io/web/others/sites.json
